import { computed, Injectable, signal } from "@angular/core"

import {
  ElectromagnetismSample,
  ElectromagnetismScenario,
  ElectromagnetismScenarioId,
  ElectromagnetismStateSnapshot,
  Vector2,
} from "./electromagnetism.models"

export type EditableElectromagnetismField =
  | "probePoint.x"
  | "probePoint.y"
  | "chargeMagnitude"
  | "secondaryChargeMagnitude"
  | "initialVelocity.x"
  | "initialVelocity.y"
  | "mass"
  | "magneticFieldStrength"
  | "current"
  | "loopRadius"
  | "plateSeparation"
  | "potentialDifference"
  | "fluxRate"
  | "inductance"

const SCENARIOS: readonly ElectromagnetismScenario[] = [
  {
    id: "point-charge-electrostatics",
    name: "Point-Charge Electrostatics",
    summary: "Inspect electric field and potential around a pair of point charges.",
    equationSummary: "F = k q1 q2 / r^2, E = F / q",
    status: "Initial slice",
    durationSeconds: 1,
    viewBounds: { minX: -6, maxX: 6, minY: -4, maxY: 4 },
    focusArea: "Coulomb force, superposed electric field, potential at a probe point",
    initialPosition: { x: 0, y: 0 },
    sourcePoint: { x: -2, y: 0 },
    secondarySourcePoint: { x: 2, y: 0 },
    probePoint: { x: 0, y: 1.5 },
    chargeMagnitude: 1,
    secondaryChargeMagnitude: -1,
  },
  {
    id: "moving-charge-magnetic-field",
    name: "Moving Charge In Magnetic Field",
    summary: "Track Lorentz-force motion for a charged particle in a uniform magnetic field.",
    equationSummary: "F = q v x B, omega = q B / m",
    status: "Initial slice",
    durationSeconds: 6,
    viewBounds: { minX: -6, maxX: 6, minY: -6, maxY: 6 },
    focusArea: "Lorentz force, cyclotron motion, trajectory curvature",
    initialPosition: { x: -3, y: 0 },
    initialVelocity: { x: 2.4, y: 1.2 },
    chargeMagnitude: 1,
    mass: 1,
    magneticFieldStrength: 1.5,
  },
  {
    id: "current-loop-magnetic-field",
    name: "Current Loop Magnetic Field",
    summary: "Estimate the magnetic field generated by a current loop near its center.",
    equationSummary: "B = mu0 I / 2R",
    status: "Implemented",
    durationSeconds: 1,
    viewBounds: { minX: -5, maxX: 5, minY: -5, maxY: 5 },
    focusArea: "Loop geometry, current strength, magnetic flux density",
    initialPosition: { x: 0, y: 0 },
    probePoint: { x: 0, y: 2 },
    current: 4,
    loopRadius: 1.8,
  },
  {
    id: "capacitor-potential-field",
    name: "Capacitor Potential Field",
    summary: "Inspect electric field strength and potential gradient between parallel plates.",
    equationSummary: "E = V / d",
    status: "Implemented",
    durationSeconds: 1,
    viewBounds: { minX: -5, maxX: 5, minY: -4, maxY: 4 },
    focusArea: "Potential difference, plate spacing, uniform field approximation",
    initialPosition: { x: 0, y: 0 },
    probePoint: { x: 0, y: 0 },
    plateSeparation: 2,
    potentialDifference: 12,
  },
  {
    id: "electromagnetic-induction",
    name: "Electromagnetic Induction",
    summary: "Estimate induced emf from a changing magnetic flux rate through a loop.",
    equationSummary: "emf = -L dPhi / dt",
    status: "Implemented",
    durationSeconds: 6,
    viewBounds: { minX: -5, maxX: 5, minY: -4, maxY: 4 },
    focusArea: "Flux change, induced emf, loop response",
    initialPosition: { x: 0, y: 0 },
    probePoint: { x: 0, y: 0 },
    fluxRate: 2.5,
    inductance: 1.2,
  },
] as const

function magnitude(vector: Vector2): number {
  return Math.hypot(vector.x, vector.y)
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max)
}

function add(left: Vector2, right: Vector2): Vector2 {
  return { x: left.x + right.x, y: left.y + right.y }
}

function buildElectrostaticField(charge: number, source: Vector2, target: Vector2): Vector2 {
  const dx = target.x - source.x
  const dy = target.y - source.y
  const distanceSquared = Math.max(dx * dx + dy * dy, 0.2)
  const distance = Math.sqrt(distanceSquared)
  const scaleFactor = (6 * charge) / (distanceSquared * distance)
  return { x: dx * scaleFactor, y: dy * scaleFactor }
}

function buildPointChargeSnapshot(
  scenario: ElectromagnetismScenario,
): ElectromagnetismStateSnapshot {
  const probePoint = scenario.probePoint ?? scenario.initialPosition
  const firstCharge = scenario.chargeMagnitude ?? 1
  const secondCharge = scenario.secondaryChargeMagnitude ?? -1
  const firstField = buildElectrostaticField(
    firstCharge,
    scenario.sourcePoint ?? { x: -2, y: 0 },
    probePoint,
  )
  const secondField = buildElectrostaticField(
    secondCharge,
    scenario.secondarySourcePoint ?? { x: 2, y: 0 },
    probePoint,
  )
  const electricField = add(firstField, secondField)
  const potential =
    (6 * firstCharge) /
      Math.max(
        Math.hypot(
          probePoint.x - (scenario.sourcePoint?.x ?? -2),
          probePoint.y - (scenario.sourcePoint?.y ?? 0),
        ),
        0.4,
      ) +
    (6 * secondCharge) /
      Math.max(
        Math.hypot(
          probePoint.x - (scenario.secondarySourcePoint?.x ?? 2),
          probePoint.y - (scenario.secondarySourcePoint?.y ?? 0),
        ),
        0.4,
      )
  const force = electricField

  return {
    timeSeconds: 0,
    position: probePoint,
    electricField,
    magneticField: { x: 0, y: 0 },
    force,
    potential,
    fieldMagnitude: magnitude(electricField),
    forceMagnitude: magnitude(force),
    energy: potential,
    stable: true,
  }
}

function buildMovingChargeSnapshot(
  scenario: ElectromagnetismScenario,
  timeSeconds = 0,
): ElectromagnetismStateSnapshot {
  const charge = scenario.chargeMagnitude ?? 1
  const mass = Math.max(scenario.mass ?? 1, 0.1)
  const magneticFieldStrength = scenario.magneticFieldStrength ?? 1
  const initialVelocity = scenario.initialVelocity ?? { x: 2.4, y: 1.2 }
  const omega = (charge * magneticFieldStrength) / mass
  let position = scenario.initialPosition
  let velocity = initialVelocity

  if (Math.abs(omega) > 1e-6) {
    const cosTheta = Math.cos(omega * timeSeconds)
    const sinTheta = Math.sin(omega * timeSeconds)
    velocity = {
      x: initialVelocity.x * cosTheta + initialVelocity.y * sinTheta,
      y: initialVelocity.y * cosTheta - initialVelocity.x * sinTheta,
    }
    position = {
      x:
        scenario.initialPosition.x +
        (initialVelocity.x * sinTheta + initialVelocity.y * (1 - cosTheta)) / omega,
      y:
        scenario.initialPosition.y +
        (initialVelocity.y * sinTheta - initialVelocity.x * (1 - cosTheta)) / omega,
    }
  } else {
    position = {
      x: scenario.initialPosition.x + initialVelocity.x * timeSeconds,
      y: scenario.initialPosition.y + initialVelocity.y * timeSeconds,
    }
  }

  const magneticField = { x: 0, y: magneticFieldStrength }
  const force = {
    x: charge * velocity.y * magneticFieldStrength,
    y: -charge * velocity.x * magneticFieldStrength,
  }

  return {
    timeSeconds,
    position,
    electricField: { x: 0, y: 0 },
    magneticField,
    force,
    potential: 0,
    fieldMagnitude: Math.abs(magneticFieldStrength),
    forceMagnitude: magnitude(force),
    energy: 0.5 * mass * magnitude(velocity) ** 2,
    stable: false,
  }
}

function buildCurrentLoopSnapshot(
  scenario: ElectromagnetismScenario,
): ElectromagnetismStateSnapshot {
  const probePoint = scenario.probePoint ?? { x: 0, y: 2 }
  const current = scenario.current ?? 0
  const loopRadius = Math.max(scenario.loopRadius ?? 1, 0.1)
  const radialDistance = Math.hypot(probePoint.x, probePoint.y)
  const magneticFieldStrength =
    (1.25663706 * current * loopRadius * loopRadius) /
    (2 * Math.pow(loopRadius * loopRadius + radialDistance * radialDistance, 1.5))

  return {
    timeSeconds: 0,
    position: probePoint,
    electricField: { x: 0, y: 0 },
    magneticField: { x: 0, y: magneticFieldStrength },
    force: { x: 0, y: 0 },
    potential: 0,
    fieldMagnitude: Math.abs(magneticFieldStrength),
    forceMagnitude: 0,
    energy: 0.5 * current * current * loopRadius,
    stable: true,
  }
}

function buildCapacitorSnapshot(scenario: ElectromagnetismScenario): ElectromagnetismStateSnapshot {
  const probePoint = scenario.probePoint ?? scenario.initialPosition
  const separation = Math.max(scenario.plateSeparation ?? 1, 0.1)
  const voltage = scenario.potentialDifference ?? 0
  const halfGap = separation / 2
  const clampedProbeX = clamp(probePoint.x, -halfGap, halfGap)
  const electricField = { x: voltage / separation, y: 0 }
  const potential = ((halfGap - clampedProbeX) / separation) * voltage
  const position = {
    x: clampedProbeX,
    y: clamp(probePoint.y, scenario.viewBounds.minY, scenario.viewBounds.maxY),
  }

  return {
    timeSeconds: 0,
    position,
    electricField,
    magneticField: { x: 0, y: 0 },
    force: electricField,
    potential,
    fieldMagnitude: magnitude(electricField),
    forceMagnitude: magnitude(electricField),
    energy: 0.5 * voltage * voltage,
    stable: true,
  }
}

function buildInductionSnapshot(
  scenario: ElectromagnetismScenario,
  timeSeconds = 0,
): ElectromagnetismStateSnapshot {
  const fluxRate = scenario.fluxRate ?? 0
  const inductance = scenario.inductance ?? 1
  const durationSeconds = Math.max(scenario.durationSeconds, 1)
  const phase = (timeSeconds / durationSeconds) * Math.PI * 2
  const magneticFlux = fluxRate * Math.sin(phase)
  const inducedEmf = -inductance * fluxRate * Math.cos(phase)

  return {
    timeSeconds,
    position: scenario.probePoint ?? scenario.initialPosition,
    electricField: { x: inducedEmf, y: 0 },
    magneticField: { x: 0, y: magneticFlux },
    force: { x: inducedEmf, y: 0 },
    potential: inducedEmf,
    fieldMagnitude: Math.abs(magneticFlux),
    forceMagnitude: Math.abs(inducedEmf),
    energy: 0.5 * inductance * fluxRate * fluxRate,
    stable: true,
  }
}

function buildSnapshot(
  scenario: ElectromagnetismScenario,
  timeSeconds = 0,
): ElectromagnetismStateSnapshot {
  if (scenario.id === "point-charge-electrostatics") {
    return buildPointChargeSnapshot(scenario)
  }

  if (scenario.id === "moving-charge-magnetic-field") {
    return buildMovingChargeSnapshot(scenario, timeSeconds)
  }

  if (scenario.id === "current-loop-magnetic-field") {
    return buildCurrentLoopSnapshot(scenario)
  }

  if (scenario.id === "capacitor-potential-field") {
    return buildCapacitorSnapshot(scenario)
  }

  return buildInductionSnapshot(scenario, timeSeconds)
}

function buildSamples(
  scenario: ElectromagnetismScenario,
  sampleCount = 24,
): readonly ElectromagnetismSample[] {
  const count = Math.max(sampleCount, 2)
  return Array.from({ length: count }, (_, index) => {
    const timeSeconds =
      scenario.id === "moving-charge-magnetic-field" || scenario.id === "electromagnetic-induction"
        ? (index / (count - 1)) * scenario.durationSeconds
        : 0
    const snapshot = buildSnapshot(scenario, timeSeconds)
    return {
      timeSeconds,
      xPosition: snapshot.position.x,
      yPosition: snapshot.position.y,
      fieldMagnitude: snapshot.fieldMagnitude,
      forceMagnitude: snapshot.forceMagnitude,
      potential: snapshot.potential,
    }
  })
}

@Injectable({ providedIn: "root" })
export class ElectromagnetismStateService {
  private readonly selectedScenarioId = signal<ElectromagnetismScenarioId>(
    "point-charge-electrostatics",
  )
  private readonly selectedTimeSeconds = signal(0)
  private readonly scenarios = signal<readonly ElectromagnetismScenario[]>(SCENARIOS)

  readonly selectedScenario = computed(
    () =>
      this.scenarios().find((scenario) => scenario.id === this.selectedScenarioId()) ??
      this.scenarios()[0],
  )
  readonly currentTimeSeconds = computed(() =>
    clamp(this.selectedTimeSeconds(), 0, this.selectedScenario().durationSeconds),
  )
  readonly currentState = computed(() =>
    buildSnapshot(this.selectedScenario(), this.currentTimeSeconds()),
  )
  readonly sampledStates = computed(() => buildSamples(this.selectedScenario()))

  listScenarios(): readonly ElectromagnetismScenario[] {
    return this.scenarios()
  }

  selectScenario(scenarioId: ElectromagnetismScenarioId): void {
    this.selectedScenarioId.set(scenarioId)
    this.selectedTimeSeconds.set(0)
  }

  updateTimeSeconds(value: number): void {
    this.selectedTimeSeconds.set(value)
  }

  updateScenarioField(field: EditableElectromagnetismField, value: number): void {
    this.scenarios.update((scenarios) =>
      scenarios.map((scenario) => {
        if (scenario.id !== this.selectedScenarioId()) {
          return scenario
        }

        if (field === "probePoint.x") {
          return {
            ...scenario,
            probePoint: {
              x: clamp(value, scenario.viewBounds.minX, scenario.viewBounds.maxX),
              y: scenario.probePoint?.y ?? scenario.initialPosition.y,
            },
          }
        }

        if (field === "probePoint.y") {
          return {
            ...scenario,
            probePoint: {
              x: scenario.probePoint?.x ?? scenario.initialPosition.x,
              y: clamp(value, scenario.viewBounds.minY, scenario.viewBounds.maxY),
            },
          }
        }

        if (field === "initialVelocity.x") {
          return {
            ...scenario,
            initialVelocity: {
              x: value,
              y: scenario.initialVelocity?.y ?? 0,
            },
          }
        }

        if (field === "initialVelocity.y") {
          return {
            ...scenario,
            initialVelocity: {
              x: scenario.initialVelocity?.x ?? 0,
              y: value,
            },
          }
        }

        return {
          ...scenario,
          chargeMagnitude: field === "chargeMagnitude" ? value : scenario.chargeMagnitude,
          secondaryChargeMagnitude:
            field === "secondaryChargeMagnitude" ? value : scenario.secondaryChargeMagnitude,
          mass: field === "mass" ? Math.max(value, 0.1) : scenario.mass,
          magneticFieldStrength:
            field === "magneticFieldStrength" ? value : scenario.magneticFieldStrength,
          current: field === "current" ? value : scenario.current,
          loopRadius: field === "loopRadius" ? Math.max(value, 0.1) : scenario.loopRadius,
          plateSeparation:
            field === "plateSeparation" ? Math.max(value, 0.1) : scenario.plateSeparation,
          potentialDifference:
            field === "potentialDifference" ? value : scenario.potentialDifference,
          fluxRate: field === "fluxRate" ? value : scenario.fluxRate,
          inductance: field === "inductance" ? Math.max(value, 0.1) : scenario.inductance,
        }
      }),
    )
  }

  importScenarioState(scenarioState: ElectromagnetismScenario, timeSeconds = 0): void {
    this.scenarios.update((scenarios) =>
      scenarios.map((scenario) =>
        scenario.id === scenarioState.id ? { ...scenarioState } : scenario,
      ),
    )
    this.selectedScenarioId.set(scenarioState.id)
    this.selectedTimeSeconds.set(timeSeconds)
  }
}
