#include "electromagnetism_core.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <stdexcept>

namespace visual_physics::electromagnetism {
namespace {

constexpr double kPi = 3.14159265358979323846;

const std::array<Scenario, 5> kDefaultScenarios{{
	{
		ScenarioId::PointChargeElectrostatics,
		"Point-Charge Electrostatics",
		"Inspect electric field and potential around a pair of point charges.",
		"F = k q1 q2 / r^2, E = F / q",
		"Implemented",
		1.0,
		{-6.0, 6.0, -4.0, 4.0},
		"Coulomb force, superposed electric field, potential at a probe point",
		{0.0, 0.0},
		std::nullopt,
		Vector2{-2.0, 0.0},
		Vector2{2.0, 0.0},
		Vector2{0.0, 1.5},
		1.0,
		-1.0,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
	},
	{
		ScenarioId::MovingChargeMagneticField,
		"Moving Charge In Magnetic Field",
		"Track Lorentz-force motion for a charged particle in a uniform magnetic field.",
		"F = q v x B, omega = q B / m",
		"Implemented",
		6.0,
		{-6.0, 6.0, -6.0, 6.0},
		"Lorentz force, cyclotron motion, trajectory curvature",
		{-3.0, 0.0},
		Vector2{2.4, 1.2},
		std::nullopt,
		std::nullopt,
		std::nullopt,
		1.0,
		std::nullopt,
		1.0,
		1.5,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
	},
	{
		ScenarioId::CurrentLoopMagneticField,
		"Current Loop Magnetic Field",
		"Estimate the magnetic field generated by a current loop near its center.",
		"B = mu0 I / 2R",
		"Implemented",
		1.0,
		{-5.0, 5.0, -5.0, 5.0},
		"Loop geometry, current strength, magnetic flux density",
		{0.0, 0.0},
		std::nullopt,
		std::nullopt,
		std::nullopt,
		Vector2{0.0, 2.0},
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		4.0,
		1.8,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
	},
	{
		ScenarioId::CapacitorPotentialField,
		"Capacitor Potential Field",
		"Inspect electric field strength and potential gradient between parallel plates.",
		"E = V / d",
		"Implemented",
		1.0,
		{-5.0, 5.0, -4.0, 4.0},
		"Potential difference, plate spacing, uniform field approximation",
		{0.0, 0.0},
		std::nullopt,
		std::nullopt,
		std::nullopt,
		Vector2{0.0, 0.0},
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		2.0,
		12.0,
		std::nullopt,
		std::nullopt,
	},
	{
		ScenarioId::ElectromagneticInduction,
		"Electromagnetic Induction",
		"Estimate induced emf from a changing magnetic flux rate through a loop.",
		"emf = -L dPhi / dt",
		"Implemented",
		6.0,
		{-5.0, 5.0, -4.0, 4.0},
		"Flux change, induced emf, loop response",
		{0.0, 0.0},
		std::nullopt,
		std::nullopt,
		std::nullopt,
		Vector2{0.0, 0.0},
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		std::nullopt,
		2.5,
		1.2,
	},
}};

double clamp(double value, double min, double max) {
	return std::min(std::max(value, min), max);
}

double magnitude(const Vector2& value) {
	return std::hypot(value.x, value.y);
}

Vector2 add(const Vector2& left, const Vector2& right) {
	return {left.x + right.x, left.y + right.y};
}

NormalizedVertex to_ndc_point(double x, double y, const Scenario& scenario) {
	const auto& bounds = scenario.view_bounds;
	const double normalized_x =
		((x - bounds.min_x) / std::max(bounds.max_x - bounds.min_x, 1e-6)) * 2.0 - 1.0;
	const double normalized_y =
		((y - bounds.min_y) / std::max(bounds.max_y - bounds.min_y, 1e-6)) * 2.0 - 1.0;

	return {
		static_cast<float>(clamp(normalized_x, -0.96, 0.96)),
		static_cast<float>(clamp(normalized_y, -0.96, 0.96)),
	};
}

Vector2 build_electrostatic_field(double charge, const Vector2& source, const Vector2& target) {
	const double dx = target.x - source.x;
	const double dy = target.y - source.y;
	const double distance_squared = std::max(dx * dx + dy * dy, 0.2);
	const double distance = std::sqrt(distance_squared);
	const double scale_factor = (6.0 * charge) / (distance_squared * distance);
	return {dx * scale_factor, dy * scale_factor};
}

Snapshot build_point_charge_snapshot(const Scenario& scenario) {
	const Vector2 probe_point = scenario.probe_point.value_or(scenario.initial_position);
	const double first_charge = scenario.charge_magnitude.value_or(1.0);
	const double second_charge = scenario.secondary_charge_magnitude.value_or(-1.0);
	const Vector2 first_source = scenario.source_point.value_or(Vector2{-2.0, 0.0});
	const Vector2 second_source = scenario.secondary_source_point.value_or(Vector2{2.0, 0.0});
	const Vector2 first_field = build_electrostatic_field(first_charge, first_source, probe_point);
	const Vector2 second_field = build_electrostatic_field(second_charge, second_source, probe_point);
	const Vector2 electric_field = add(first_field, second_field);
	const double potential =
		6.0 * first_charge / std::max(std::hypot(probe_point.x - first_source.x, probe_point.y - first_source.y), 0.4) +
		6.0 * second_charge / std::max(std::hypot(probe_point.x - second_source.x, probe_point.y - second_source.y), 0.4);

	return {
		0.0,
		probe_point,
		electric_field,
		{0.0, 0.0},
		electric_field,
		potential,
		magnitude(electric_field),
		magnitude(electric_field),
		potential,
		true,
	};
}

Snapshot build_moving_charge_snapshot(const Scenario& scenario, double time_seconds) {
	const double charge = scenario.charge_magnitude.value_or(1.0);
	const double mass = std::max(scenario.mass.value_or(1.0), 0.1);
	const double magnetic_field_strength = scenario.magnetic_field_strength.value_or(1.0);
	const Vector2 initial_velocity = scenario.initial_velocity.value_or(Vector2{2.4, 1.2});
	const double omega = (charge * magnetic_field_strength) / mass;
	Vector2 position = scenario.initial_position;
	Vector2 velocity = initial_velocity;

	if (std::abs(omega) > 1e-6) {
		const double cos_theta = std::cos(omega * time_seconds);
		const double sin_theta = std::sin(omega * time_seconds);
		velocity = {
			initial_velocity.x * cos_theta + initial_velocity.y * sin_theta,
			initial_velocity.y * cos_theta - initial_velocity.x * sin_theta,
		};
		position = {
			scenario.initial_position.x +
				(initial_velocity.x * sin_theta + initial_velocity.y * (1.0 - cos_theta)) / omega,
			scenario.initial_position.y +
				(initial_velocity.y * sin_theta - initial_velocity.x * (1.0 - cos_theta)) / omega,
		};
	} else {
		position = {
			scenario.initial_position.x + initial_velocity.x * time_seconds,
			scenario.initial_position.y + initial_velocity.y * time_seconds,
		};
	}

	const Vector2 magnetic_field{0.0, magnetic_field_strength};
	const Vector2 force{
		charge * velocity.y * magnetic_field_strength,
		-charge * velocity.x * magnetic_field_strength,
	};

	return {
		time_seconds,
		position,
		{0.0, 0.0},
		magnetic_field,
		force,
		0.0,
		std::abs(magnetic_field_strength),
		magnitude(force),
		0.5 * mass * magnitude(velocity) * magnitude(velocity),
		false,
	};
}

Snapshot build_current_loop_snapshot(const Scenario& scenario) {
	const Vector2 probe_point = scenario.probe_point.value_or(Vector2{0.0, 2.0});
	const double current = scenario.current.value_or(0.0);
	const double loop_radius = std::max(scenario.loop_radius.value_or(1.0), 0.1);
	const double radial_distance = std::hypot(probe_point.x, probe_point.y);
	const double magnetic_field_strength =
		(1.25663706 * current * loop_radius * loop_radius) /
		(2.0 * std::pow(loop_radius * loop_radius + radial_distance * radial_distance, 1.5));

	return {
		0.0,
		probe_point,
		{0.0, 0.0},
		{0.0, magnetic_field_strength},
		{0.0, 0.0},
		0.0,
		std::abs(magnetic_field_strength),
		0.0,
		0.5 * current * current * loop_radius,
		true,
	};
}

Snapshot build_capacitor_snapshot(const Scenario& scenario) {
	const Vector2 probe_point = scenario.probe_point.value_or(scenario.initial_position);
	const double separation = std::max(scenario.plate_separation.value_or(1.0), 0.1);
	const double voltage = scenario.potential_difference.value_or(0.0);
	const double half_gap = separation / 2.0;
	const double clamped_probe_x = clamp(probe_point.x, -half_gap, half_gap);
	const Vector2 electric_field{voltage / separation, 0.0};
	const double potential = ((half_gap - clamped_probe_x) / separation) * voltage;
	const Vector2 position{
		clamped_probe_x,
		clamp(probe_point.y, scenario.view_bounds.min_y, scenario.view_bounds.max_y),
	};

	return {
		0.0,
		position,
		electric_field,
		{0.0, 0.0},
		electric_field,
		potential,
		magnitude(electric_field),
		magnitude(electric_field),
		0.5 * voltage * voltage,
		true,
	};
}

Snapshot build_induction_snapshot(const Scenario& scenario, double time_seconds) {
	const double flux_rate = scenario.flux_rate.value_or(0.0);
	const double inductance = scenario.inductance.value_or(1.0);
	const double duration_seconds = std::max(scenario.duration_seconds, 1.0);
	const double phase = (time_seconds / duration_seconds) * kPi * 2.0;
	const double magnetic_flux = flux_rate * std::sin(phase);
	const double induced_emf = -inductance * flux_rate * std::cos(phase);

	return {
		time_seconds,
		scenario.probe_point.value_or(scenario.initial_position),
		{induced_emf, 0.0},
		{0.0, magnetic_flux},
		{induced_emf, 0.0},
		induced_emf,
		std::abs(magnetic_flux),
		std::abs(induced_emf),
		0.5 * inductance * flux_rate * flux_rate,
		true,
	};
}

void append_rectangle(
	std::vector<NormalizedVertex>& vertices,
	double x,
	double y,
	double width,
	double height,
	const Scenario& scenario) {
	vertices.push_back(to_ndc_point(x, y, scenario));
	vertices.push_back(to_ndc_point(x + width, y, scenario));
	vertices.push_back(to_ndc_point(x + width, y, scenario));
	vertices.push_back(to_ndc_point(x + width, y + height, scenario));
	vertices.push_back(to_ndc_point(x + width, y + height, scenario));
	vertices.push_back(to_ndc_point(x, y + height, scenario));
	vertices.push_back(to_ndc_point(x, y + height, scenario));
	vertices.push_back(to_ndc_point(x, y, scenario));
}

}  // namespace

std::string_view to_string(ScenarioId id) {
	switch (id) {
	case ScenarioId::PointChargeElectrostatics:
		return "point-charge-electrostatics";
	case ScenarioId::MovingChargeMagneticField:
		return "moving-charge-magnetic-field";
	case ScenarioId::CurrentLoopMagneticField:
		return "current-loop-magnetic-field";
	case ScenarioId::CapacitorPotentialField:
		return "capacitor-potential-field";
	case ScenarioId::ElectromagneticInduction:
		return "electromagnetic-induction";
	}

	throw std::runtime_error("Unknown electromagnetism scenario id");
}

std::optional<ScenarioId> parse_scenario_id(std::string_view value) {
	if (value == "point-charge-electrostatics") {
		return ScenarioId::PointChargeElectrostatics;
	}
	if (value == "moving-charge-magnetic-field") {
		return ScenarioId::MovingChargeMagneticField;
	}
	if (value == "current-loop-magnetic-field") {
		return ScenarioId::CurrentLoopMagneticField;
	}
	if (value == "capacitor-potential-field") {
		return ScenarioId::CapacitorPotentialField;
	}
	if (value == "electromagnetic-induction") {
		return ScenarioId::ElectromagneticInduction;
	}
	return std::nullopt;
}

Scenario make_default_scenario(ScenarioId id) {
	const auto match = std::find_if(
		kDefaultScenarios.begin(),
		kDefaultScenarios.end(),
		[id](const Scenario& scenario) { return scenario.id == id; });
	if (match == kDefaultScenarios.end()) {
		throw std::runtime_error("Unsupported electromagnetism scenario id");
	}
	return *match;
}

Snapshot sample_scenario(const Scenario& scenario, double time_seconds) {
	switch (scenario.id) {
	case ScenarioId::PointChargeElectrostatics:
		return build_point_charge_snapshot(scenario);
	case ScenarioId::MovingChargeMagneticField:
		return build_moving_charge_snapshot(scenario, time_seconds);
	case ScenarioId::CurrentLoopMagneticField:
		return build_current_loop_snapshot(scenario);
	case ScenarioId::CapacitorPotentialField:
		return build_capacitor_snapshot(scenario);
	case ScenarioId::ElectromagneticInduction:
		return build_induction_snapshot(scenario, time_seconds);
	}

	throw std::runtime_error("Unsupported electromagnetism scenario id");
}

std::vector<Sample> build_samples(const Scenario& scenario, std::size_t sample_count) {
	const std::size_t resolved_sample_count = std::max<std::size_t>(sample_count, 2);
	std::vector<Sample> samples;
	samples.reserve(resolved_sample_count);
	for (std::size_t index = 0; index < resolved_sample_count; index += 1) {
		const double time_seconds =
			(scenario.id == ScenarioId::MovingChargeMagneticField ||
			 scenario.id == ScenarioId::ElectromagneticInduction)
				? (static_cast<double>(index) / static_cast<double>(resolved_sample_count - 1)) *
					scenario.duration_seconds
				: 0.0;
		const Snapshot snapshot = sample_scenario(scenario, time_seconds);
		samples.push_back({
			time_seconds,
			snapshot.position.x,
			snapshot.position.y,
			snapshot.field_magnitude,
			snapshot.force_magnitude,
			snapshot.potential,
		});
	}
	return samples;
}

std::vector<NormalizedVertex> build_axes_vertices(const Scenario& scenario) {
	return {
		to_ndc_point(scenario.view_bounds.min_x, 0.0, scenario),
		to_ndc_point(scenario.view_bounds.max_x, 0.0, scenario),
		to_ndc_point(0.0, scenario.view_bounds.min_y, scenario),
		to_ndc_point(0.0, scenario.view_bounds.max_y, scenario),
	};
}

std::vector<NormalizedVertex> build_marker_vertices(
	const Snapshot& snapshot,
	const Scenario& scenario,
	float aspect_ratio) {
	const auto center = to_ndc_point(snapshot.position.x, snapshot.position.y, scenario);
	const float half_width = 0.022F;
	const float safe_aspect = std::max(aspect_ratio, 0.001F);
	const float half_height = aspect_ratio >= 1.0F ? half_width * aspect_ratio : half_width / safe_aspect;

	return {
		{center.x - half_width, center.y - half_height},
		{center.x + half_width, center.y - half_height},
		{center.x - half_width, center.y + half_height},
		{center.x - half_width, center.y + half_height},
		{center.x + half_width, center.y - half_height},
		{center.x + half_width, center.y + half_height},
	};
}

std::vector<NormalizedVertex> build_scenario_vertices(
	const Snapshot& snapshot,
	const Scenario& scenario) {
	std::vector<NormalizedVertex> vertices;
	auto append_line = [&](const Vector2& start, const Vector2& end) {
		vertices.push_back(to_ndc_point(start.x, start.y, scenario));
		vertices.push_back(to_ndc_point(end.x, end.y, scenario));
	};

	if (scenario.id == ScenarioId::PointChargeElectrostatics) {
		append_line(scenario.source_point.value_or(Vector2{-2.0, 0.0}), snapshot.position);
		append_line(scenario.secondary_source_point.value_or(Vector2{2.0, 0.0}), snapshot.position);
		return vertices;
	}

	if (scenario.id == ScenarioId::MovingChargeMagneticField) {
		append_rectangle(vertices, -2.8, -2.8, 5.6, 5.6, scenario);
		return vertices;
	}

	if (scenario.id == ScenarioId::CurrentLoopMagneticField) {
		const double radius = scenario.loop_radius.value_or(1.8);
		for (int index = 0; index < 32; index += 1) {
			const double start_angle = (static_cast<double>(index) / 32.0) * kPi * 2.0;
			const double end_angle = (static_cast<double>(index + 1) / 32.0) * kPi * 2.0;
			append_line(
				{std::cos(start_angle) * radius, std::sin(start_angle) * radius},
				{std::cos(end_angle) * radius, std::sin(end_angle) * radius});
		}
		return vertices;
	}

	if (scenario.id == ScenarioId::CapacitorPotentialField) {
		const double half_gap = std::max(scenario.plate_separation.value_or(2.0) / 2.0, 0.4);
		append_line({-half_gap, -2.5}, {-half_gap, 2.5});
		append_line({half_gap, -2.5}, {half_gap, 2.5});
		return vertices;
	}

	append_rectangle(vertices, -1.8, -1.8, 3.6, 3.6, scenario);
	append_rectangle(vertices, -1.1, -1.1, 2.2, 2.2, scenario);
	return vertices;
}

}  // namespace visual_physics::electromagnetism