name: Build visual-physics-angular-ui
on:
  pull_request:
    paths:
      - .github/workflows/build-visual-physics-angular-ui.yaml
      - visual-physics-angular-ui/**
    types:
      - opened
      - reopened
      - synchronize

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: visual-physics-angular-ui/package.json
        
      - name: Install dependencies
        shell: bash
        working-directory: visual-physics-angular-ui
        run: npm ci

      - name: Check code formatting
        id: check_format
        continue-on-error: true
        shell: bash
        working-directory: visual-physics-angular-ui
        run: npm run check-format

      - name: Show format logs on check failure
        if: steps.check_format.outcome == 'failure'
        shell: bash
        working-directory: visual-physics-angular-ui
        run: |
          npm run format
          exit 1

      - name: Run ESLint
        shell: bash
        working-directory: visual-physics-angular-ui
        run: npm run lint

      - name: Build visual-physics-angular-ui
        shell: bash
        working-directory: visual-physics-angular-ui
        run: npm run build
